name: Ping Render

on:
  schedule:
    - cron: "*/5 * * * *"   # a cada 5 minutos
  workflow_dispatch:        # permite rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Health Endpoint
        run: |
          curl -s https://bling-webhook.onrender.com/health
``
